package de.take_weiland.mods.commons.internal;

import java.io.File;
import java.net.URISyntaxException;
import java.util.Arrays;

import net.minecraftforge.common.MinecraftForge;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLConstructionEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import de.take_weiland.mods.commons.internal.updater.UpdateController;
import de.take_weiland.mods.commons.internal.updater.UpdateControllerLocal;

public class CommonsModContainer extends DummyModContainer {

	private UpdateController updateController;
	
	public static SevenCommonsProxy proxy;
	public static CommonsModContainer instance;
	
	public CommonsModContainer() {
		super(new ModMetadata());
		ModMetadata meta = getMetadata();
		meta.name = "SevenCommons";
		meta.modId = "sevencommons";
		meta.authorList = Arrays.asList("diesieben07");
		meta.version = "1.0";
		
		meta.description = "Provides various Utilities for other mods.";
		
		meta.autogenerated = false;
		
		instance = this;
	}
	
	public UpdateController getLocalUpdateController() {
		return updateController;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		bus.register(this);
		
		return true;
	}
	
	@Subscribe
	public void constructing(FMLConstructionEvent event) {
		try { // my version of @SidedProxy
			if (event.getSide().isServer()) {
				proxy = (SevenCommonsProxy) Class.forName("de.take_weiland.mods.commons.internal.ServerProxy").newInstance();
			} else {
				proxy = (SevenCommonsProxy) Class.forName("de.take_weiland.mods.commons.internal.client.ClientProxy").newInstance();
			}
		} catch (ReflectiveOperationException e) {
			// nope
			e.printStackTrace();
		}
	}
	
	@Subscribe
	public void preInit(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(proxy);
	}
	
	@Subscribe
	public void postInit(FMLPostInitializationEvent event) {
		updateController = new UpdateControllerLocal();
	}

	private static File source;
	
	static {
		try {
			source = new File(CommonsModContainer.class.getProtectionDomain().getCodeSource().getLocation().toURI());
			System.out.println(source + " " + source.isDirectory());
		} catch (URISyntaxException e) {
			// Ummm ?
			e.printStackTrace();
		}
	}
	
	@Override
	public File getSource() {
		return source;
	}

	@Override
	public Class<?> getCustomResourcePackClass() {
		if (source == null) {
			return null;
		}
		try {
			return source.isDirectory() ? Class.forName("de.take_weiland.mods.commons.internal.CommonsFolderResourcePack") : Class.forName("de.take_weiland.mods.commons.internal.CommonsFileResourcePack");
		} catch (ClassNotFoundException e) {
			return null;
		} 
	}
}
