package de.take_weiland.mods.commons.internal;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import de.take_weiland.mods.commons.updater.UpdateController;

public class CommonsModContainer extends DummyModContainer {

	private UpdateController updateController;
	
	public CommonsModContainer() {
		super(new ModMetadata());
		ModMetadata meta = getMetadata();
		meta.modId = meta.name = "SevenCommons";
		meta.authorList = Arrays.asList("diesieben07");
		meta.version = "1.0";
		
		meta.description = "Provides various Utilities for other mods.";
		
		meta.autogenerated = false;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		bus.register(this);
		
		return true;
	}
	
	@Subscribe
	public void postInit(FMLPostInitializationEvent event) {
		updateController = new UpdateController();
		updateController.searchForUpdates(Loader.instance().getIndexedModList().get("testmod"));
	}
	
}
