package de.take_weiland.mods.commons.internal.exclude;

import com.google.common.collect.ImmutableList;
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.client.FMLFileResourcePack;
import cpw.mods.fml.client.FMLFolderResourcePack;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import de.take_weiland.mods.commons.config.ConfigInjector;
import de.take_weiland.mods.commons.config.GetProperty;
import de.take_weiland.mods.commons.internal.PacketInventoryName;
import de.take_weiland.mods.commons.internal.ServerProxy;
import de.take_weiland.mods.commons.internal.SevenCommons;
import de.take_weiland.mods.commons.internal.SevenCommonsProxy;
import de.take_weiland.mods.commons.internal.client.ClientProxy;
import de.take_weiland.mods.commons.net.Network;
import de.take_weiland.mods.commons.net.PacketHandler;
import net.minecraftforge.common.Configuration;

import java.io.File;

public final class SCModContainer extends DummyModContainer {

	public static long clientMainThreadID;

	public static SevenCommonsProxy proxy;
	public static SCModContainer instance;

	@GetProperty(comment = "Set to false to disable the auto-updating feature of SevenCommons")
	public static boolean updaterEnabled = true;

	public static PacketHandler packets;
	public static final int SYNC_PACKET_ID = 0;

	public SCModContainer() {
		super(new ModMetadata());
		ModMetadata meta = getMetadata();
		meta.name = "SevenCommons";
		meta.modId = "sevencommons";
		meta.authorList = ImmutableList.of("diesieben07");
		meta.version = SevenCommons.VERSION;

		meta.description = "Provides various Utilities for other mods.";

		meta.autogenerated = false;

		instance = this;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller) {
		bus.register(this);
		return true;
	}

	@SideOnly(Side.CLIENT)
	@Subscribe
	public void clientPreInit(FMLPreInitializationEvent event) {
		proxy = new ClientProxy();
		clientMainThreadID = Thread.currentThread().getId();
		universalPreInit(event);
	}

	@SideOnly(Side.SERVER)
	@Subscribe
	public void serverPreInit(FMLPreInitializationEvent event) {
		proxy = new ServerProxy();
		universalPreInit(event);
	}

	public void universalPreInit(FMLPreInitializationEvent event) {
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		ConfigInjector.inject(config, getClass());

		packets = Network.newChannel("SevenCommons")
				.register(PacketInventoryName.class)
				.build();

		ClassInfoUtil.preInit();

		proxy.preInit(event);
	}

	@Override
	public File getSource() {
		return SevenCommons.source;
	}

	@Override
	public Class<?> getCustomResourcePackClass() {
		return getSource().isDirectory() ? FMLFolderResourcePack.class : FMLFileResourcePack.class;
	}

}
